spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 07fefe7d172c94efbe60
            client-secret: bb3f63997d9aad6b09b8813f5a5d64db70ffe29f